"""add render job logs

Revision ID: 44a116ed488e
Revises: 738d123a32a9
Create Date: 2026-07-09 14:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a116ed488e'
down_revision = '738d123a32a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('render_jobs', sa.Column('logs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('render_jobs', 'logs')
    # ### end Alembic commands ###
