"""add project agent_state

Revision ID: 738d123a32a9
Revises: e82569df0396
Create Date: 2026-07-09 08:42:16.055206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738d123a32a9'
down_revision = 'e82569df0396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('agent_state', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'agent_state')
    # ### end Alembic commands ###
