"""add_user_credits_and_plan

Revision ID: e82569df0396
Revises: f05bcf5eea61
Create Date: 2026-07-08 15:32:03.691127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e82569df0396'
down_revision = 'f05bcf5eea61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credits', sa.Integer(), server_default='10', nullable=False))
    op.add_column('users', sa.Column('plan', sa.String(), server_default='free', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    op.drop_column('users', 'credits')
    # ### end Alembic commands ###
